force-app/main/default/objects/Timetrack_Category__c/Timetrack_Category__c.object-meta.xml
<CustomObject>
    <label>Time Track Category</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Track Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timetrack_Category__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Timetrack_Category__c/fields/Disabled__c.field-meta.xml
<CustomField>
    <fullName>Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If disabled, it cannot be selected when creating new time tracking entries</inlineHelpText>
    <label>Disabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Timetrack_Entry__c/Timetrack_Entry__c.object-meta.xml
<CustomObject>
    <label>Time Track Entry</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Track Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Timetrack_Entry__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Time Track Entries</relationshipLabel>
    <relationshipName>Time_Track_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timetrack_Entry__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Time Track Entries</relationshipLabel>
    <relationshipName>Time_Track_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timetrack_Entry__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Timetrack_Category__c</referenceTo>
    <relationshipLabel>Time Track Entries</relationshipLabel>
    <relationshipName>Time_Track_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timetrack_Entry__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Timetrack_Entry__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Duration of the task in millisecods</inlineHelpText>
    <label>Duration (ms)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Timetrack_Entry__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Timetrack_Entry__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>Used to associate the record with other entities, which will be solved in apex</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timetrack_Entry__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Timetrack_Entry__c/fields/Stopwatch_Start__c.field-meta.xml
<CustomField>
    <fullName>Stopwatch_Start__c</fullName>
    <label>Stopwatch Start</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TimetrackController.cls
public with sharing class TimetrackController {
	/*
	 * @description:
	 */
    @AuraEnabled
	public static TimetrackInfo getTimetrackInfo() {
		try {
			TimetrackInfo info = new TimetrackInfo();
			info.categories = selectCategories();
			info.entries = selectEntries();

			return info;
		} catch (Exception e) {
			System.debug(e.getMessage() + '\r\n' + e.getStackTraceString());
			throw new AuraHandledException(e.getMessage());
		}
	}

	/*
	 * @description:
	 */
    @AuraEnabled
	public static Timetrack_Entry__c saveTimetrackEntry(Id timetrackEntryId, String name, Id categoryId) {
		try {
			Timetrack_Entry__c entry = new Timetrack_Entry__c(
				Id = timetrackEntryId,
				Name = name,
				Category__c = categoryId
			);
			upsert entry;

			entry = selectTimetrackEntryById(entry.Id);

			return entry;
		} catch (Exception e) {
			System.debug(e.getMessage() + '\r\n' + e.getStackTraceString());
			throw new AuraHandledException(e.getMessage());
		}
	}

	/*
	 * @description:
	 */
    @AuraEnabled
	public static Timetrack_Entry__c completeTimetrackEntry(Id timetrackEntryId) {
		try {
			Timetrack_Entry__c entry = selectTimetrackEntryById(timetrackEntryId);
			if(entry == null) return null;

			if(entry.Start_Date__c == null) entry.Start_Date__c = DateTime.now();
			if(entry.Duration__c == null) entry.Duration__c = 0;
			Long fifteenMinutes = 15 * 60 * 1000;
			Long difference = Math.mod((Long)entry.Duration__c,fifteenMinutes);
			if(difference != 0) {
				entry.Duration__c += fifteenMinutes - difference;
			}
			entry.Completed__c = true;
			entry.End_Date__c = DateTime.now();

			update entry;

			return entry;
		} catch (Exception e) {
			System.debug(e.getMessage() + '\r\n' + e.getStackTraceString());
			throw new AuraHandledException(e.getMessage());
		}
	}

	/*
	 * @description:
	 */
    @AuraEnabled
	public static Timetrack_Entry__c uncompleteTimetrackEntry(Id timetrackEntryId) {
		try {
			Timetrack_Entry__c entry = selectTimetrackEntryById(timetrackEntryId);
			if(entry == null) return null;

			if(entry.Duration__c == 0) entry.Start_Date__c = null;
			entry.Completed__c = false;
			entry.End_Date__c = null;

			update entry;

			return entry;
		} catch (Exception e) {
			System.debug(e.getMessage() + '\r\n' + e.getStackTraceString());
			throw new AuraHandledException(e.getMessage());
		}
	}

	/*
	 * @description:
	 */
    @AuraEnabled
	public static Timetrack_Entry__c startTimetrackEntry(Id timetrackEntryId, Long epoch) {
		try {
			Timetrack_Entry__c entry = selectTimetrackEntryById(timetrackEntryId);
			if(entry == null) return null;

			entry.Stopwatch_Start__c = epoch;
			if(entry.Start_Date__c == null) entry.Start_Date__c = DateTime.now();

			update entry;

			return entry;
		} catch (Exception e) {
			System.debug(e.getMessage() + '\r\n' + e.getStackTraceString());
			throw new AuraHandledException(e.getMessage());
		}
	}

	/*
	 * @description:
	 */
    @AuraEnabled
	public static Timetrack_Entry__c resetTimetrackEntry(Id timetrackEntryId) {
		try {
			Timetrack_Entry__c entry = selectTimetrackEntryById(timetrackEntryId);
			if(entry == null) return null;

			entry.Stopwatch_Start__c = null;
			entry.Duration__c = 0;
			entry.Start_Date__c = null;
			entry.End_Date__c = null;

			update entry;

			return entry;
		} catch (Exception e) {
			System.debug(e.getMessage() + '\r\n' + e.getStackTraceString());
			throw new AuraHandledException(e.getMessage());
		}
	}

	/*
	 * @description:
	 */
    @AuraEnabled
	public static Timetrack_Entry__c stopTimetrackEntry(Id timetrackEntryId, Long epoch) {
		try {
			Timetrack_Entry__c entry = selectTimetrackEntryById(timetrackEntryId);
			if(entry == null) return null;

			if(entry.Stopwatch_Start__c == null) entry.Stopwatch_Start__c = 0;
			if(entry.Duration__c == null) entry.Duration__c = 0;
			Long totalTime = epoch - (Long)entry.Stopwatch_Start__c;

			entry.Duration__c += totalTime;
			entry.Stopwatch_Start__c = null;

			update entry;

			return entry;
		} catch (Exception e) {
			System.debug(e.getMessage() + '\r\n' + e.getStackTraceString());
			throw new AuraHandledException(e.getMessage());
		}
	}

	/*
	 * @description:
	 */
    @AuraEnabled
	public static Timetrack_Entry__c setTimetrackDescription(Id timetrackEntryId, String description) {
		try {
			Timetrack_Entry__c entry = selectTimetrackEntryById(timetrackEntryId);
			if(entry == null) return null;

			entry.Description__c = description;

			update entry;

			return entry;
		} catch (Exception e) {
			System.debug(e.getMessage() + '\r\n' + e.getStackTraceString());
			throw new AuraHandledException(e.getMessage());
		}
	}

	/*
	 * @description:
	 */
    @AuraEnabled
	public static Timetrack_Entry__c associateTimetrackWithRecord(Id timetrackEntryId, Id recordId) {
		try {
			Timetrack_Entry__c entry = selectTimetrackEntryById(timetrackEntryId);
			if(entry == null) return null;

			entry.Record_Id__c = recordId;
			if(recordId != null) {
				if(recordId.getSobjectType() == Case.getSObjectType()) {
					entry.Case__c = recordId;
					entry.Account__c = null;
				}
				else if(recordId.getSobjectType() == Account.getSObjectType()) {
					entry.Account__c = recordId;
					entry.Case__c = null;
				}
			}
			else {
				entry.Case__c = null;
				entry.Account__c = null;
			}

			update entry;

			entry = selectTimetrackEntryById(timetrackEntryId);
			if(entry.Case__c != null && entry.Case__r.AccountId != null && entry.Account__c == null) {
				entry.Account__c = entry.Case__r.AccountId;
				update entry;
				entry = selectTimetrackEntryById(timetrackEntryId);
			}

			return entry;
		} catch (Exception e) {
			System.debug(e.getMessage() + '\r\n' + e.getStackTraceString());
			throw new AuraHandledException(e.getMessage());
		}
	}

	/*
	 * @description:
	 */
    @AuraEnabled
	public static void deleteTimetrackEntry(Id timetrackEntryId) {
		try {
			Timetrack_Entry__c entry = new Timetrack_Entry__c(
				Id = timetrackEntryId
			);
			delete entry;
		} catch (Exception e) {
			System.debug(e.getMessage() + '\r\n' + e.getStackTraceString());
			throw new AuraHandledException(e.getMessage());
		}
	}

	/*
	 * @description:
	 */
    @AuraEnabled
	public static Timetrack_Entry__c addMillisecondsToTimetrackEntry(Id timetrackEntryId, Long ms) {
		try {
			Timetrack_Entry__c entry = selectTimetrackEntryById(timetrackEntryId);
			if(entry == null) return null;

			if(entry.Duration__c == null) entry.Duration__c = 0;
			entry.Duration__c += ms;

			update entry;

			return entry;
		} catch (Exception e) {
			System.debug(e.getMessage() + '\r\n' + e.getStackTraceString());
			throw new AuraHandledException(e.getMessage());
		}
	}

	/*
	 * @description:
	 */
	public class TimetrackInfo {
		@AuraEnabled
		public List<Timetrack_Category__c> categories {get; set;}

		@AuraEnabled
		public List<Timetrack_Entry__c> entries {get; set;}
	}

	// SELECTORS

	/*
	 * @description:
	 */
	private static List<Timetrack_Category__c> selectCategories() {
		return [
			select
				Id,
				Name,
				Description__c
			from
				Timetrack_Category__c
			where
				Disabled__c = false
		];
	}

	/*
	 * @description:
	 */
	private static List<Timetrack_Entry__c> selectEntries() {
		return [
			select
				Id,
				Name,
				Category__c,
				Category__r.Name,
				Duration__c,
				Completed__c,
				Start_Date__c,
				End_Date__c,
				Stopwatch_Start__c,
				Description__c,
				Record_Id__c,
				Case__c,
				Case__r.CaseNumber,
				Case__r.AccountId,
				Account__c,
				Account__r.Name
			from
				Timetrack_Entry__c
			where
				OwnerId = :UserInfo.getUserId() and
				(Completed__c = false or End_Date__c = TODAY or End_Date__c = THIS_WEEK)
		];
	}

	/*
	 * @description:
	 */
	private static Timetrack_Entry__c selectTimetrackEntryById(Id entryId) {
		List<Timetrack_Entry__c> entries = [
			select
				Id,
				Name,
				Category__c,
				Category__r.Name,
				Duration__c,
				Completed__c,
				Start_Date__c,
				End_Date__c,
				Stopwatch_Start__c,
				Description__c,
				Record_Id__c,
				Case__c,
				Case__r.CaseNumber,
				Case__r.AccountId,
				Account__c,
				Account__r.Name
			from
				Timetrack_Entry__c
			where
				Id = :entryId
		];

		return !entries.isEmpty() ? entries[0] : null;
	}
}